name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - uses: actions/checkout@v3

      - name: Build
        run: make build

      - name: Test
        run: make test
        env:
          RP_SECRET: "secret"
          RP_ROOT_URL: "http://127.0.0.1:{{ port }}/"
